import { startPortal, launch } from './mock-portal.mjs';
import { chromium } from 'playwright-core';
const portal = await startPortal();
const browser = await launch(chromium);
const page = await browser.newPage();
page.on('console', (m) => console.log('[console]', m.text().slice(0, 1200)));
page.on('pageerror', (e) => console.log('[pageerror]', String(e).slice(0, 1200)));
await page.goto(`${portal.base}/?mock=live&theme=mountain`);
await page.waitForTimeout(2500);
await browser.close();
portal.close();
